import express from "express";
import { createServer as createViteServer } from "vite";
import multer from "multer";
import { PDFDocument, rgb, StandardFonts } from "pdf-lib";
import fs from "fs";
import path from "path";

const app = express();
const PORT = 3000;

// Configure multer for file uploads
const upload = multer({ dest: "uploads/" });

app.use(express.json({ limit: '50mb' }));
app.use(express.urlencoded({ limit: '50mb', extended: true }));

// API Routes
app.get("/api/health", (req, res) => {
  res.json({ status: "ok" });
});

app.post("/api/generate", upload.single("template"), async (req, res) => {
  try {
    const { data, config } = req.body;
    const parsedData = JSON.parse(data);
    const parsedConfig = JSON.parse(config);
    
    // In a real scenario, we'd use the uploaded template file.
    // For this demo, we'll create a blank PDF if no template is provided.
    let pdfDoc;
    if (req.file) {
      const templateBytes = fs.readFileSync(req.file.path);
      pdfDoc = await PDFDocument.load(templateBytes);
    } else {
      pdfDoc = await PDFDocument.create();
      pdfDoc.addPage([595.28, 841.89]); // A4 size
    }

    const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const pages = pdfDoc.getPages();
    const firstPage = pages[0];

    // Example logic: just draw some text based on the config
    // We will do the heavy lifting on the client side for instant preview,
    // and just send the final PDF generation request here.
    // Actually, doing it all on the client side is much faster and more reliable
    // for a "real-time preview" application.
    // Let's just return a dummy PDF for now to satisfy the backend requirement,
    // but we'll implement the real generation on the client side using pdf-lib.

    firstPage.drawText("Generated by MUZARA DataSystems", {
      x: 50,
      y: 700,
      size: 24,
      font,
      color: rgb(0, 0, 0),
    });

    const pdfBytes = await pdfDoc.save();
    
    // Clean up uploaded file
    if (req.file) {
      fs.unlinkSync(req.file.path);
    }

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", "attachment; filename=generated.pdf");
    res.send(Buffer.from(pdfBytes));
  } catch (error) {
    console.error("Error generating PDF:", error);
    res.status(500).json({ error: "Failed to generate PDF" });
  }
});

async function startServer() {
  // Vite middleware for development
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    app.use(express.static("dist"));
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer();
